# Generated by Django 2.2.7 on 2021-01-03 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Money_status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('money_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Rice_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rice_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tractor', models.CharField(max_length=1000)),
                ('tractor_status', models.CharField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Tractor_status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tractor_status', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Work_status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=1000)),
                ('lng', models.CharField(max_length=1000)),
                ('area', models.IntegerField()),
                ('other', models.CharField(max_length=1000)),
                ('workDetail', models.CharField(max_length=1000)),
                ('RepairTime', models.CharField(max_length=1000)),
                ('Harverstime', models.CharField(max_length=1000)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('money', models.IntegerField()),
                ('farmer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Farmer')),
                ('money_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Money_status')),
                ('rice_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Rice_type')),
                ('tractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tractor')),
                ('tractor_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tractor_status')),
                ('work_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Work_status')),
            ],
        ),
    ]
