# Generated by Django 3.1.7 on 2021-04-21 09:53

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(max_length=1000, verbose_name='ชื่อ-สกุล')),
                ('image', models.ImageField(upload_to='images/farmer', verbose_name='รูปโปรไฟล์')),
                ('address', models.CharField(max_length=1000, verbose_name='ที่อยู่')),
                ('phone', models.CharField(max_length=1000, verbose_name='เบอร์โทรศัพท์')),
                ('email', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'เกษตรกร',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'ตารางงานรถเกี่ยวนวดข้าว',
            },
        ),
        migrations.CreateModel(
            name='Money_status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('money_status', models.CharField(max_length=100, verbose_name='สถานะการชำระเงิน')),
            ],
            options={
                'verbose_name': 'สถานะการชำระเงิน',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=1000, verbose_name='ชื่อ-สกุล')),
                ('image', models.ImageField(upload_to='media/', verbose_name='รูปโปรไฟล์')),
                ('address', models.CharField(max_length=1000, verbose_name='ที่อยู่')),
                ('phone', models.CharField(max_length=1000, verbose_name='เบอร์โทรศัพท์')),
                ('email', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'เจ้าของรถ',
            },
        ),
        migrations.CreateModel(
            name='Rice_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rice_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ลักษณะข้าวที่จะให้เกี่ยว',
            },
        ),
        migrations.CreateModel(
            name='Tractor_status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tractor_status', models.CharField(max_length=1000, verbose_name='สถานะรถเกี่ยวนวดข้าว')),
            ],
            options={
                'verbose_name': 'สถานะรถเกี่ยวนวดข้าว',
            },
        ),
        migrations.CreateModel(
            name='Work_status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work_status', models.CharField(max_length=100, verbose_name='สถานะงาน')),
            ],
            options={
                'verbose_name': 'สถานะงาน',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=1000, verbose_name='ละติจูด')),
                ('lng', models.CharField(max_length=1000, verbose_name='ลองติจูด')),
                ('area', models.CharField(max_length=1000, verbose_name='พื้นที่ (ไร่)')),
                ('rice', models.CharField(max_length=1000, null=True, verbose_name='พันธุ์ข้าว')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('workDetail', models.TextField(max_length=1000, null=True, verbose_name='รายละเอียด')),
                ('price', models.CharField(max_length=1000, null=True, verbose_name='จำนวนเงิน (บาท)')),
                ('farmer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='เกษตรกร')),
                ('money_status', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.money_status', verbose_name='สถานะการชำระเงิน')),
                ('rice_type', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rice_type', verbose_name='ลักษณะข้าวที่จะให้เกี่ยว')),
                ('work_status', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.work_status', verbose_name='สถานะงาน')),
            ],
            options={
                'verbose_name': 'งานที่ต้องเก็บเกี่ยว',
            },
        ),
        migrations.CreateModel(
            name='AddTractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tractor_name', models.CharField(max_length=1000)),
                ('tractor_detail', models.CharField(max_length=1000)),
                ('tractor_timeHarvers', models.CharField(max_length=1000)),
                ('tractor_timeRepair', models.CharField(max_length=1000)),
                ('tractor_status', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tractor_status')),
            ],
            options={
                'verbose_name': 'เพิ่มข้อมูลรถเกี่ยวนวดข้าว',
            },
        ),
    ]
