# Generated by Django 2.2.7 on 2021-01-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tractor',
            old_name='owner',
            new_name='owner_name',
        ),
    ]
