# Generated by Django 2.2.7 on 2020-12-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractor',
            name='work_id',
            field=models.CharField(max_length=1000),
        ),
    ]
