# Generated by Django 2.2.7 on 2021-02-17 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='work',
            name='date_start',
        ),
        migrations.AlterField(
            model_name='work',
            name='money_status',
            field=models.ForeignKey(default=' ', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Money_status', verbose_name='สถานะการชำระเงิน'),
        ),
        migrations.AlterField(
            model_name='work',
            name='rice',
            field=models.CharField(max_length=1000, null=True, verbose_name='พันธุ์ข้าว'),
        ),
        migrations.AlterField(
            model_name='work',
            name='workDetail',
            field=models.TextField(max_length=1000, null=True, verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_status',
            field=models.ForeignKey(default=' ', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Work_status', verbose_name='สถานะงาน'),
        ),
    ]
