# Generated by Django 2.2.7 on 2021-02-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='work',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='work',
            name='money_status',
        ),
        migrations.RemoveField(
            model_name='work',
            name='price',
        ),
        migrations.RemoveField(
            model_name='work',
            name='work_status',
        ),
        migrations.AlterField(
            model_name='work',
            name='area',
            field=models.CharField(max_length=1000, null=True, verbose_name='พื้นที่ (ไร่)'),
        ),
        migrations.AlterField(
            model_name='work',
            name='rice',
            field=models.CharField(max_length=1000, null=True, verbose_name='พันธุ์ข้าว'),
        ),
        migrations.AlterField(
            model_name='work',
            name='workDetail',
            field=models.TextField(max_length=1000, null=True, verbose_name='รายละเอียด'),
        ),
    ]
