# Generated by Django 2.2.7 on 2021-02-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210225_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='image',
            field=models.ImageField(default='images/farmer/admin.png', upload_to='images/farmer', verbose_name='รูปโปรไฟล์'),
        ),
    ]
