# Generated by Django 2.2.7 on 2021-02-15 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210216_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtractor',
            name='tractor_img',
        ),
        migrations.RemoveField(
            model_name='addtractor',
            name='tractor_owner',
        ),
    ]
