# Generated by Django 2.2.7 on 2021-02-16 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210217_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='money_status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Money_status', verbose_name='สถานะการชำระเงิน'),
        ),
        migrations.AddField(
            model_name='work',
            name='price',
            field=models.CharField(max_length=1000, null=True, verbose_name='จำนวนเงิน (บาท)'),
        ),
        migrations.AddField(
            model_name='work',
            name='work_status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Work_status', verbose_name='สถานะงาน'),
        ),
    ]
