# Generated by Django 2.2.7 on 2021-02-15 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210216_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='money_status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Money_status', verbose_name='สถานะการชำระเงิน'),
        ),
    ]
