# Generated by Django 2.2.7 on 2021-01-05 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_tractor_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractor',
            name='tractor_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tractor_status'),
        ),
    ]
